CREATE TABLE IF NOT EXISTS rel_Veterinario_Grupo( 
    CRMV INTEGER PRIMARY KEY 
        FOREIGN KEY CRMV REFERENCES veterinario(CRMV) ON DELETE CASCADE,  
    idGrupo INTEGER PRIMARY KEY 
        FOREIGN KEY idGrupo REFERENCES grupo(idGrupo) ON DELETE CASCADE
);